### ISSUE TITLE
CDDA atrac3 tracks .bin usage

### ISSUE THREAD

**Issue by PeatearB** [zecoxao/psxtract#1]
How do you use the decoded CDDA atrac3 tracks? They don't open in Sony Sound Forge.

**Comment by zecoxao** [comment]
you need to convert them to wav first in order to listen to them, using the ps3 atrac3 conversion tool in the oficial sdk. i cannot provide links to it, but it's out there, just google "ps3+ps4 sdk" and you should find it

**Comment by PeatearB** [comment]
Thanks for the response. I worked it out by adding a 132 Kbps, 44,100 Hz Stereo Atrac3 header to the files.
